defaults:
  - dataset: dataset_toy_arm
  - model: model_toy_arm

wandb:
  name: jacobian_fields
  entity: scene-representation-group
  project: self-model
  mode: online
  group: null
  tags: null

dataset:
  overfit_to_scene: null

training:
  data:
    batch_size: 7
    num_workers: 16
    rays_per_batch: 1024
  optim:
    lr: 1e-4
    warm_up_steps: 10000

  val_check_interval: 1000
  max_steps: 50000000  # 50 million steps

validation:
  data:
    batch_size: 1
    num_workers: 4
    rays_per_batch: null
  video:
    frequency: 0.25
    num_frames: 30
    frame_rate: 30

checkpoint:
  every_n_train_steps: 5000
  load: null

